# Generated by Django 3.1.7 on 2021-03-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210312_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_Alerts',
        ),
        migrations.DeleteModel(
            name='Model_Auth_Group',
        ),
    ]
