# Generated by Django 3.2 on 2021-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOfficialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='Путь к файлу')),
                ('name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('date_auto_remove', models.DateTimeField(verbose_name='Дата и время удаления файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'sys_reports',
                'managed': False,
            },
        ),
    ]
