version: '3.3'

services:
  web:
    restart: always
    image: saphir2.4
    volumes:
      - /devstorage:/devstorage
    expose:
      - 8000
  nginx:
    restart: always
    image: saphir_nginx
    volumes:
      - /devstorage:/devstorage
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
