version: '3.3'

services:
  web:
    restart: always
    image: saphir_3
    volumes:
      - /deploy_storage:/deploy_storage
    expose:
      - 9000
  nginx:
    restart: always
    image: saphir_3_nginx
    volumes:
      - /deploy_storage:/deploy_storage
    ports:
      - "7000:7000"
    depends_on:
      - web
