version: '3.3'

services:
  web:
    restart: always
    image: saphir_2
    volumes:
      - /deploy_storage:/deploy_storage
    expose:
      - 8000
  nginx:
    restart: always
    image: saphir_nginx
    volumes:
      - /deploy_storage:/deploy_storage
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
