# Generated by Django 3.2 on 2021-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='Поле заполняется в автоматическом режиме.', verbose_name='Дата создания уведомления')),
                ('type', models.CharField(choices=[('information', 'информация'), ('warning', 'предупреждение'), ('error', 'ошибка')], max_length=14, verbose_name='Тип уведомления')),
                ('content', models.TextField(verbose_name='Тест сообщения')),
                ('geometry', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'sys_notify',
                'managed': False,
            },
        ),
    ]
