# Generated by Django 3.2 on 2021-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.BooleanField(default=False, help_text='Являются ли данные в классификаторе специфичными', verbose_name='Специфический параметр')),
                ('need', models.BooleanField(default=False, help_text='Является ли данный классификатор обязательным для объекта', verbose_name='Основное поле')),
                ('type_val', models.CharField(choices=[('number', 'Число'), ('text', 'Текст'), ('datatime', 'Дата/Время'), ('date', 'Дата'), ('checkbox', 'Да/Нет'), ('geometry', 'Точка/Путь/Полигон')], default='text', help_text='К какому типу будет относиться вносимое значение', max_length=10, verbose_name='Формат')),
                ('name', models.CharField(blank=True, help_text='Данное сокращение будет использоваться при написании скриптов', max_length=25, null=True, verbose_name='Имя латиницей')),
                ('title', models.CharField(max_length=50, verbose_name='Имя классификатора')),
                ('hint', models.CharField(blank=True, help_text='Дополнительная информация для пользователя, который будет вносить данные', max_length=255, null=True, verbose_name='Всплывающая подсказка')),
                ('descript', models.CharField(blank=True, help_text='Дополнительная информация о классификаторе для администраторов', max_length=255, null=True, verbose_name='Дополнительные пометки')),
            ],
            options={
                'verbose_name': 'Классификатор',
                'verbose_name_plural': 'Классификаторы',
                'db_table': 'sys_key',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя латиницей')),
                ('title', models.CharField(max_length=50, verbose_name='Имя списка')),
            ],
            options={
                'verbose_name': 'Список',
                'verbose_name_plural': 'Списки',
                'db_table': 'sys_list_top',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelListDop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=255, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Поле списка',
                'verbose_name_plural': 'Поля списков',
                'db_table': 'sys_list_dop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Имя объекта')),
                ('title_single', models.CharField(max_length=25, verbose_name='Имя объекта ед.ч.')),
                ('name', models.CharField(max_length=25, verbose_name='Имя латиницей')),
                ('descript', models.CharField(blank=True, help_text='Дополнительная информация о объекте', max_length=255, null=True, verbose_name='Дополнительные пометки')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': 'sys_obj',
                'managed': False,
            },
        ),
    ]
