# Generated by Django 2.2.7 on 2020-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Auth_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='model_alerts',
            options={'managed': False, 'verbose_name': 'уведомление', 'verbose_name_plural': 'уведомления'},
        ),
    ]
